package PhoneGap: s/icon/appicon/ & use autoScaleIcon

diff --git a/package/PhoneGap/Android/build b/package/PhoneGap/Android/build
--- a/package/PhoneGap/Android/build
+++ b/package/PhoneGap/Android/build
@@ -55,9 +55,21 @@ cp -R phonegap/xml android-project/res/
 # setup icons
 while read px dpi; do
   if test -d android-project/res/drawable-$dpi; then
-    if test -e android-project/assets/theme/images/icon-$px.png; then
-      cp android-project/assets/theme/images/icon-$px.png \
+    if test -e android-project/assets/theme/images/appicon-$px.png; then
+      cp android-project/assets/theme/images/appicon-$px.png \
           android-project/res/drawable-$dpi/ic_launcher.png
+    elif test "${autoScaleIcon-false}" = true; then
+      if test -e android-project/assets/theme/images/appicon.png; then
+        convert android-project/assets/theme/images/appicon.png \
+            -resize ${px}x$px \
+            android-project/res/drawable-$dpi/ic_launcher.png
+      else
+        echo "Warning: missing appicon.png to autoScaleIcon" >&2
+        continue
+      fi
+    else
+      echo "Warning: missing appicon-$px.png and autoScaleIcon is not true" >&2
+      continue
     fi
   else
     echo "Skipping $dpi" >&2
diff --git a/package/PhoneGap/iOS/setup-icons b/package/PhoneGap/iOS/setup-icons
--- a/package/PhoneGap/iOS/setup-icons
+++ b/package/PhoneGap/iOS/setup-icons
@@ -6,17 +6,29 @@ set -xeuf
 /usr/libexec/PlistBuddy -x -c "Add :CFBundleIconFiles array" \
     iOS-project/$activity/$activity-info.plist
 while read px name; do
-  if test -e src/theme/images/icon-$px.png; then
-    cp src/theme/images/icon-$px.png \
+  if test -e src/theme/images/appicon-$px.png; then
+    cp src/theme/images/appicon-$px.png \
         iOS-project/$activity/Resources/icons/$name
-    /usr/libexec/PlistBuddy -x -c "Add :CFBundleIconFiles: string $name" \
-        iOS-project/$activity/$activity-info.plist
+  elif test "${autoScaleIcon-false}" = true; then
+    if test -e src/theme/images/appicon.png; then
+      convert src/theme/images/appicon.png \
+          -resize ${px}x$px \
+          iOS-project/$activity/Resources/icons/$name
+    else
+      echo "Warning: missing appicon.png to autoScaleIcon" >&2
+      continue
+    fi
+  else
+    echo "Warning: missing appicon-$px.png and autoScaleIcon is not true" >&2
+    continue
   fi
+  /usr/libexec/PlistBuddy -x -c "Add :CFBundleIconFiles: string $name" \
+      iOS-project/$activity/$activity-info.plist
 done<<EOF
- 57 icon.png
-114 icon@2x.png
- 72 icon-72.png
- 29 icon-Small.png
- 50 icon-Small-50.png
- 58 icon-Small@2x.png
+ 57 appicon.png
+114 appicon@2x.png
+ 72 appicon-72.png
+ 29 appicon-Small.png
+ 50 appicon-Small-50.png
+ 58 appicon-Small@2x.png
 EOF
